#FROM ubuntu:latest
#LABEL authors="asus"
#
#ENTRYPOINT ["top", "-b"]

# TODO need to
   #install nvm
   #install nodejs
   #install (npm install: [tailwindcss, chart.js, react-chartjs-2, axios, react-router-dom])

#