services:
  backend-dev:
    container_name: fastapi-backend
    build:
        context: ./backend
        dockerfile: Dockerfile
    environment:
      DEBUG: 1
    volumes:
      - ./backend/api:/backend/api
    expose:
      - '8000'
    ports:
      - '8000:8000'
#    command: uvicorn main:app --host 0.0.0.0 --reload
    working_dir: /api
    command: python -m uvicorn main:app --host 0.0.0.0 --port 80 --reload
#
#  frontend-dev:
#    build:
#      context: ./frontend
#      dockerfile: Dockerfile
#    environment:
#      CHOKIDAR_USEPOLLING: "true" # hot-reload
#    volumes:
#      - ./frontend/src:/frontend/src
#    expose:
#      - '5173'
#    ports:
#      - '5173:5173'
#    command: npm run dev
